language: rust
sudo: false

cache: cargo

rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    apt:
        packages:
            - libssl-dev

before_script: |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo install cargo-tarpaulin
    fi

script:
    - cargo clean
    - cargo build --verbose --all
    - cargo test --verbose --all

after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    fi

notifications:
    email:
        on_success: never
