pub mod build;
pub mod colors;
pub mod continents;
pub mod event_details;
#[deprecated = "No longer responds to requests, use v2::events instead"]
pub mod event_names;
pub mod files;
pub mod guild_details;
pub mod item_details;
pub mod items;
pub mod map_floor;
pub mod map_names;
pub mod maps;
pub mod recipe_details;
pub mod recipes;
pub mod skin_details;
pub mod skins;
pub mod world_names;
pub mod wvw;
